# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: 西片的笔记

theme:
  name: material
  language: zh
  custom_dir: overrides
  features:
    - navigation.indexes

nav:
  - 主页: index.md
  - 博客:
      - 博客首页: blog/index.md
      - 标签: blog/tags.md

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-3YGC1WJLL9

plugins:
  - search
  - meta
  - blog:
      enabled: true
      blog_dir: blog
      blog_toc: false
      post_dir: "{blog}/posts"
      post_url_max_categories: 1
      post_slugify_separator: "-"
      post_excerpt_max_authors: 1
      post_excerpt_max_categories: 5
      post_excerpt_separator: <!-- more -->
      post_readtime: true
      post_readtime_words_per_minute: 265
      archive: true
      archive_name: 归档
      archive_pagination: true
      archive_pagination_per_page: 10
      archive_toc: false
      categories: true
      categories_name: 分类
      categories_slugify_separator: "-"
      categories_pagination: true
      categories_pagination_per_page: 10
      categories_toc: false
      authors: true
      authors_file: "{blog}/.authors.yml"
      authors_profiles_name: 作者
      authors_profiles_pagination: true
      authors_profiles_pagination_per_page: 10
      authors_profiles_toc: false
      pagination: true
      pagination_per_page: 10
      pagination_keep_content: false
      draft: true
      draft_on_serve: true
      draft_if_future_date: false
      post_date_format: full
      archive_date_format: MM/dd/yyyy
      authors_profiles: true
  - social:
      cards_layout_options:
        background_color: "#ff1493"
        logo: assets/images/avatar.png
  - tags:
      tags_file: blog/tags.md
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - optimize:
      enabled: true
      cache: true
      cache_dir: .cache/plugins/optimize
      optimize_png: true
      optimize_png_speed: 4
      optimize_png_strip: true
      optimize_jpg: true
      optimize_jpg_quality: 60
      optimize_jpg_progressive: true
      print_gain: true
      print_gain_summary: true
